#!/usr/bin/env bash

PORT=${1:-65432}
sudo docker rm -f feedproxy 2>/dev/null || true

sudo docker run -d \
  --name feedproxy \
  --restart=on-failure:5 \
  -p ${PORT}:${PORT} \
  -e PORT=${PORT} \
  feedproxy

sudo docker logs --tail 100 -f feedproxy
